package:
  name: dataaug
  version: 0.0.1
source:
  sha256: f7672f36280fd277249a0b791c94a31d21f16065431029c9bb3450cbc625d8c0
  url: https://files.pythonhosted.org/packages/89/0e/a4dfe1fd3c81a75916a0c280ca86e5540e92e7546f59e26023ec6a0df94c/dataaug-0.0.1.tar.gz
about:
  dev_url: https://noklam.github.io
  doc_url: https://noklam.github.io
  home: https://noklam.github.io
  license: Apache Software
  license_family: APACHE
  summary: A data augmentation library for tabular and time series data.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - noklam
requirements:
  host:
  - pip
  - python
  - packaging
  run:
  - pip
  - python
  - packaging
test:
  imports:
  - dataaug
